version: "3.8"

services:
  web:
    build: .
    container_name: ci4_web
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./logs:/var/www/html/writable/logs
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: ci4_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ci4_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db_data:
